# ─────────────────────────────────────────────────────────────────────────────
# Site Identity
# ─────────────────────────────────────────────────────────────────────────────
title: "Caitlin Chee-Kirkpatrick"
masthead_title: "Caitlin Chee-Kirkpatrick"
description: "Data & BI Analyst — Python, SQL, Power BI. Portfolio + blog."
locale: "en-CA"
timezone: "America/Toronto"

# Primary URL (use your .ca). Keep baseurl empty for a root-domain site.
url: "https://caitlincheekirkpatrick.ca"
baseurl: ""

# Theme & look
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"       # other nice options: default, dark, mint
search: true                       # client-side search (lunr)
breadcrumbs: true
permalink: /:categories/:title/

# GitHub repo metadata (helps with links)
repository: "caitlincheekirkpatrick/caitlincheekirkpatrick.github.io"

# ─────────────────────────────────────────────────────────────────────────────
# Author Profile (shows on posts/pages)
# ─────────────────────────────────────────────────────────────────────────────
author:
  name: "Caitlin Chee-Kirkpatrick"
  avatar: "/assets/img/headshot.jpg"   # add later (optional)
  bio: "Data & BI analyst building decision-ready dashboards and Python/SQL automations."
  email: "caitlincheekirkpatrick@gmail.com"
  links:
    - label: "Portfolio"
      url: "https://caitlincheekirkpatrick.ca"
    - label: "GitHub"
      url: "https://github.com/caitlincheekirkpatrick"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/caitlincheekirkpatrick"
    - label: "Resume"
      url: "/resume.pdf"

# ─────────────────────────────────────────────────────────────────────────────
# Plugins supported by GitHub Pages
# ─────────────────────────────────────────────────────────────────────────────
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO/OpenGraph (optional social preview image)
# logo: "/assets/img/og-card.png"

# Defaults to keep posts/pages consistent
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: false
      related: true
      toc: true
      toc_sticky: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Build settings
markdown: kramdown
exclude:
  - README.md
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock

# Feeds & sitemap are auto-generated by plugins above
